language: objective-c

before_install:
- gem install cocoapods
- npm install -g bower
- bower install
- bundle install
- bundle exec middleman build

script:
- make cov

after_success:
- sudo easy_install cpp-coveralls
- make coveralls
